#!/bin/bash

if [[ $1 == "" ]]; then
    echo "plz give the branch name"
fi

bash get_jobs_info.sh $1
python3 download_logs_2.py $1 
python3 log_analysis.py logs/$1/  > Result_$1  #with instrumentation

#python3 log_analysis.py logs/one-run-to-find-them-all/  #w/o instrumentation

#IF you want to merge the result csv with the without instrumentation, then run the following command. Otherwise comment
python3 merge_two_csv.py  AutoGeneratedGithubAction-1677165960-c4e224e.csv AutoGeneratedGithubAction-one-run-to-find-them-all.csv "Master-AutoGeneratedGithubAction-$1.csv"
cut -d',' -f2- "Master-AutoGeneratedGithubAction-$1.csv" > tmp.csv
cat tmp.csv > "Master-AutoGeneratedGithubAction-$1.csv"
rm tmp.csv
